package net.earthmc.routefinder.ice;

import com.google.gson.*;
import net.earthmc.routefinder.teleport.*;

import java.io.*;
import java.net.URI;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;

/** Offline copy of XiLeF2211's MIT-licensed EarthMC Ice Highway Map. */
public final class IceRoadNetwork {
    public record Station(int id,String name,String type,double x,double z,String notes,List<String> lines){}
    public record Segment(double x1,double z1,double x2,double z2,int color,String company,String line){}
    public record Point(double x,double z){}
    public record Trip(int entryId,int exitId,String entry,String exit,double entryX,double entryZ,double exitX,double exitZ,double roadDistance,double effectiveDistance,List<Segment> path,List<Integer> stationIds){}
    private record Edge(int to,double distance,List<Point> path,int color,String company,String line){}
    private record Search(double[] distance,Edge[] next){}
    private record Projection(int segment,double t,Point point,double distanceSquared){}
    private record PathEdge(int to,double distance){}
    private static final String UPDATE_URL="https://raw.githubusercontent.com/XiLeF2211/ice-highways-map/main/nostra/highways.json";
    private static final long UPDATE_INTERVAL_MS=30L*60L*1000L;
    private static final HttpClient HTTP=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).followRedirects(HttpClient.Redirect.NORMAL).build();
    private static final AtomicBoolean UPDATING=new AtomicBoolean();
    private static volatile long lastUpdateAttempt;
    private static volatile IceRoadNetwork instance=load();
    private final List<Station> stations;private final List<Segment> segments;private final List<List<Edge>> graph;
    private IceRoadNetwork(List<Station>s,List<Segment>l,List<List<Edge>>g){stations=s;segments=l;graph=g;}
    public static IceRoadNetwork get(){return instance;}
    public List<Station> stations(){return stations;}public List<Segment> segments(){return segments;}

    private static IceRoadNetwork load(){
        try(InputStream in=IceRoadNetwork.class.getResourceAsStream("/assets/earthmcroutefinder/ice_roads/highways.json")){
            if(in==null)return empty();return parse(JsonParser.parseReader(new InputStreamReader(in,StandardCharsets.UTF_8)).getAsJsonObject());
        }catch(Exception e){return empty();}
    }
    private static IceRoadNetwork parse(JsonObject root){
        try{
            JsonArray rawStations=root.getAsJsonArray("stations");List<Station> stations=new ArrayList<>(rawStations.size());
            for(JsonElement el:rawStations){JsonObject s=el.getAsJsonObject();int id=s.get("id").getAsInt();while(stations.size()<=id)stations.add(null);List<String> lines=new ArrayList<>();JsonObject companies=s.has("lines")&&s.get("lines").isJsonObject()?s.getAsJsonObject("lines"):new JsonObject();for(var company:companies.entrySet())if(company.getValue().isJsonObject())for(String line:company.getValue().getAsJsonObject().keySet())lines.add(company.getKey()+": "+line);stations.set(id,new Station(id,text(s,"name","Station "+id),text(s,"type","station"),number(s,"x"),number(s,"z"),text(s,"notes",""),List.copyOf(lines)));}
            List<Segment> segments=new ArrayList<>();List<Map<Integer,Edge>> edges=new ArrayList<>();for(int i=0;i<stations.size();i++)edges.add(new HashMap<>());
            JsonObject companies=root.getAsJsonObject("lines");for(var company:companies.entrySet())for(var line:company.getValue().getAsJsonObject().entrySet()){JsonObject ld=line.getValue().getAsJsonObject();int color=parseColor(text(ld,"color","FFFFFF"));JsonObject branches=ld.getAsJsonObject("branches");for(var branch:branches.entrySet()){JsonObject bd=branch.getValue().getAsJsonObject();JsonArray vertices=bd.getAsJsonArray("vertices");List<Point> points=new ArrayList<>();for(JsonElement vertex:vertices){JsonArray v=vertex.getAsJsonArray();points.add(new Point(v.get(0).getAsDouble(),v.get(1).getAsDouble()));}for(int i=1;i<points.size();i++){Point a=points.get(i-1),b=points.get(i);segments.add(new Segment(a.x,a.z,b.x,b.z,color,company.getKey(),line.getKey()));}JsonArray ids=bd.getAsJsonArray("stations");List<Integer> flat=new ArrayList<>();for(JsonElement id:ids){JsonElement value=id.isJsonArray()?id.getAsJsonArray().get(0):id;if(value.isJsonPrimitive()&&value.getAsJsonPrimitive().isNumber())flat.add(value.getAsInt());}for(int i=1;i<flat.size();i++){int a=flat.get(i-1),b=flat.get(i);if(a<0||b<0||a>=stations.size()||b>=stations.size()||stations.get(a)==null||stations.get(b)==null)continue;List<Point> path=edgePath(stations.get(a),stations.get(b),points);double d=pathDistance(path);putEdge(edges.get(a),new Edge(b,d,path,color,company.getKey(),line.getKey()));List<Point> reverse=new ArrayList<>(path);Collections.reverse(reverse);putEdge(edges.get(b),new Edge(a,d,List.copyOf(reverse),color,company.getKey(),line.getKey()));}}}
            List<List<Edge>> graph=new ArrayList<>();for(Map<Integer,Edge> e:edges)graph.add(List.copyOf(e.values()));return new IceRoadNetwork(List.copyOf(stations),List.copyOf(segments),List.copyOf(graph));
        }catch(Exception e){throw new IllegalArgumentException("Invalid ice-highway dataset",e);}
    }
    /** Non-blocking live refresh. Called from the client tick; network and parsing work stay off-thread. */
    public static void tickAutoUpdate(){long now=System.currentTimeMillis();if(now-lastUpdateAttempt<UPDATE_INTERVAL_MS||!UPDATING.compareAndSet(false,true))return;lastUpdateAttempt=now;HttpRequest request=HttpRequest.newBuilder(URI.create(UPDATE_URL)).timeout(Duration.ofSeconds(20)).header("User-Agent","EarthMCRouteFinder/1.4.5").GET().build();HTTP.sendAsync(request,HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8)).whenComplete((response,error)->{try{if(error!=null||response==null||response.statusCode()!=200){net.earthmc.routefinder.RouteFinderMod.LOGGER.warn("[TownyMap] Ice-highway update failed: {}",error==null?"HTTP "+(response==null?"?":response.statusCode()):error.toString());return;}IceRoadNetwork updated=parse(JsonParser.parseString(response.body()).getAsJsonObject());long stationCount=updated.stations.stream().filter(Objects::nonNull).count();if(stationCount<100||updated.segments.size()<500)throw new IllegalArgumentException("dataset unexpectedly small");instance=updated;ROUTE_TRIPS.clear();net.earthmc.routefinder.RouteFinderMod.LOGGER.info("[TownyMap] Ice highways updated live: {} stations, {} segments",stationCount,updated.segments.size());}catch(Exception e){net.earthmc.routefinder.RouteFinderMod.LOGGER.warn("[TownyMap] Rejected ice-highway update; keeping current data: {}",e.toString());}finally{UPDATING.set(false);}});}
    private static IceRoadNetwork empty(){return new IceRoadNetwork(List.of(),List.of(),List.of());}
    private static void putEdge(Map<Integer,Edge> edges,Edge edge){edges.merge(edge.to,edge,(a,b)->a.distance<=b.distance?a:b);}
    static List<Point> edgePath(Station a,Station b,List<Point> vertices){if(vertices.size()<2)return List.of(new Point(a.x,a.z),new Point(b.x,b.z));List<Point> nodes=new ArrayList<>();Map<String,Integer> indexes=new HashMap<>();for(Point point:vertices)nodeIndex(nodes,indexes,point);int start=nodeIndex(nodes,indexes,new Point(a.x,a.z)),goal=nodeIndex(nodes,indexes,new Point(b.x,b.z));List<Projection> from=closestProjections(a,vertices),to=closestProjections(b,vertices);for(Projection p:from)nodeIndex(nodes,indexes,p.point);for(Projection p:to)nodeIndex(nodes,indexes,p.point);List<List<PathEdge>> graph=new ArrayList<>();for(int i=0;i<nodes.size();i++)graph.add(new ArrayList<>());for(int i=0;i<vertices.size()-1;i++){Point left=vertices.get(i),right=vertices.get(i+1);List<Integer> onSegment=new ArrayList<>();for(int n=0;n<nodes.size();n++)if(onSegment(nodes.get(n),left,right))onSegment.add(n);onSegment.sort(Comparator.comparingDouble(n->segmentPosition(nodes.get(n),left,right)));for(int n=1;n<onSegment.size();n++)connect(graph,nodes,onSegment.get(n-1),onSegment.get(n));}for(Projection p:from)connect(graph,nodes,start,indexes.get(pointKey(p.point)));for(Projection p:to)connect(graph,nodes,goal,indexes.get(pointKey(p.point)));double[] distances=new double[nodes.size()];int[] previous=new int[nodes.size()];Arrays.fill(distances,Double.POSITIVE_INFINITY);Arrays.fill(previous,-1);distances[start]=0;PriorityQueue<double[]> queue=new PriorityQueue<>(Comparator.comparingDouble(v->v[1]));queue.add(new double[]{start,0});while(!queue.isEmpty()){double[] current=queue.poll();int at=(int)current[0];if(current[1]!=distances[at])continue;if(at==goal)break;for(PathEdge edge:graph.get(at)){double next=current[1]+edge.distance;if(next<distances[edge.to]){distances[edge.to]=next;previous[edge.to]=at;queue.add(new double[]{edge.to,next});}}}if(!Double.isFinite(distances[goal]))return List.of(new Point(a.x,a.z),new Point(b.x,b.z));List<Point> path=new ArrayList<>();for(int at=goal;at>=0;at=previous[at]){path.add(nodes.get(at));if(at==start)break;}Collections.reverse(path);return List.copyOf(path);}
    private static List<Projection> closestProjections(Station station,List<Point> vertices){List<Projection> all=new ArrayList<>();double best=Double.POSITIVE_INFINITY;for(int i=0;i<vertices.size()-1;i++){Point a=vertices.get(i),b=vertices.get(i+1);double dx=b.x-a.x,dz=b.z-a.z,lengthSquared=dx*dx+dz*dz;double t=lengthSquared==0?0:Math.max(0,Math.min(1,((station.x-a.x)*dx+(station.z-a.z)*dz)/lengthSquared));Point p=new Point(a.x+dx*t,a.z+dz*t);double ex=station.x-p.x,ez=station.z-p.z,d2=ex*ex+ez*ez;all.add(new Projection(i,t,p,d2));best=Math.min(best,d2);}double limit=best+.01;return all.stream().filter(p->p.distanceSquared<=limit).toList();}
    private static int nodeIndex(List<Point> nodes,Map<String,Integer> indexes,Point point){String key=pointKey(point);Integer found=indexes.get(key);if(found!=null)return found;int index=nodes.size();nodes.add(point);indexes.put(key,index);return index;}
    private static String pointKey(Point point){return Math.round(point.x*1000)+":"+Math.round(point.z*1000);}
    private static boolean onSegment(Point p,Point a,Point b){double dx=b.x-a.x,dz=b.z-a.z,cross=(p.x-a.x)*dz-(p.z-a.z)*dx;if(Math.abs(cross)>Math.max(1,Math.hypot(dx,dz))*.001)return false;double t=segmentPosition(p,a,b);return t>=-.000001&&t<=1.000001;}
    private static double segmentPosition(Point p,Point a,Point b){double dx=b.x-a.x,dz=b.z-a.z,length=dx*dx+dz*dz;return length==0?0:((p.x-a.x)*dx+(p.z-a.z)*dz)/length;}
    private static void connect(List<List<PathEdge>> graph,List<Point> nodes,int a,int b){if(a==b)return;double d=distance(nodes.get(a).x,nodes.get(a).z,nodes.get(b).x,nodes.get(b).z);graph.get(a).add(new PathEdge(b,d));graph.get(b).add(new PathEdge(a,d));}
    private static void addPoint(List<Point> points,Point point){if(points.isEmpty()||distance(points.getLast().x,points.getLast().z,point.x,point.z)>.001)points.add(point);}
    /** A source branch may leave a junction and return to the same junction before continuing. Such a
     * closed excursion cannot improve a station-to-station route and renders as an unexplained spur. */
    static List<Point> removeClosedDetours(List<Point> path){List<Point> out=new ArrayList<>();Map<String,Integer> seen=new HashMap<>();for(Point point:path){String key=Math.round(point.x*1000)+":"+Math.round(point.z*1000);Integer earlier=seen.get(key);if(earlier!=null){for(int i=out.size()-1;i>earlier;i--){Point removed=out.remove(i);seen.remove(Math.round(removed.x*1000)+":"+Math.round(removed.z*1000));}}else{seen.put(key,out.size());out.add(point);}}return out;}
    private static double pathDistance(List<Point> path){double d=0;for(int i=1;i<path.size();i++)d+=distance(path.get(i-1).x,path.get(i-1).z,path.get(i).x,path.get(i).z);return d;}
    boolean edgePathsAreSimple(){for(List<Edge> edges:graph)for(Edge edge:edges){Set<String> seen=new HashSet<>();for(Point point:edge.path)if(!seen.add(pointKey(point)))return false;}return true;}
    private static String text(JsonObject o,String k,String f){return o.has(k)&&o.get(k).isJsonPrimitive()?o.get(k).getAsString():f;}private static double number(JsonObject o,String k){return o.has(k)?o.get(k).getAsDouble():0;}private static int parseColor(String s){try{return 0xFF000000|Integer.parseInt(s,16);}catch(Exception e){return 0xFFFFFFFF;}}private static double distance(double x1,double z1,double x2,double z2){return Math.hypot(x2-x1,z2-z1);}

    static boolean canEnterOrExit(Station station){if(station==null)return false;String type=station.type().toLowerCase(Locale.ROOT);return !type.startsWith("elev")&&!type.startsWith("jct");}
    private static boolean usableEndpoint(Station station,Map<String,String> reports,boolean accessibleOnly){if(!canEnterOrExit(station))return false;String status=reports.getOrDefault(reportKey(station.id),"UNKNOWN");return !"OBSTRUCTED".equals(status)&&(!accessibleOnly||"ACCESSIBLE".equals(status));}
    public Station nearest(double x,double z,Map<String,String>reports){return nearest(x,z,reports,false);}
    public Station nearest(double x,double z,Map<String,String>reports,boolean accessibleOnly){Station best=null;double bd=Double.POSITIVE_INFINITY;for(Station s:stations){if(!usableEndpoint(s,reports,accessibleOnly))continue;double d=distance(x,z,s.x,s.z);if(d<bd){bd=d;best=s;}}return best;}
    public static String reportKey(int id){return "ICE_STATION:"+id;}
    public Trip trip(double fromX,double fromZ,double toX,double toZ,Map<String,String>reports){return trip(fromX,fromZ,toX,toZ,reports,false);}
    public Trip trip(double fromX,double fromZ,double toX,double toZ,Map<String,String>reports,boolean accessibleOnly){Station target=nearest(toX,toZ,reports,accessibleOnly);return target==null?null:bestTrip(fromX,fromZ,toX,toZ,target,dijkstra(target.id,reports),reports,accessibleOnly);}
    private Trip bestTrip(double fromX,double fromZ,double toX,double toZ,Station target,Search search,Map<String,String>reports,boolean accessibleOnly){Station entry=null;double best=distance(fromX,fromZ,toX,toZ);for(Station s:stations){if(!usableEndpoint(s,reports,accessibleOnly)||!Double.isFinite(search.distance[s.id]))continue;double effective=distance(fromX,fromZ,s.x,s.z)+search.distance[s.id]/8.0+distance(target.x,target.z,toX,toZ);if(effective<best){best=effective;entry=s;}}if(entry==null)return null;List<Segment> path=new ArrayList<>();List<Integer> stationIds=new ArrayList<>();stationIds.add(entry.id);int at=entry.id,guard=0;while(at!=target.id&&guard++<stations.size()){Edge e=search.next[at];if(e==null)break;for(int i=1;i<e.path.size();i++){Point a=e.path.get(i-1),b=e.path.get(i);path.add(new Segment(a.x,a.z,b.x,b.z,e.color,e.company,e.line));}at=e.to;stationIds.add(at);}return new Trip(entry.id,target.id,entry.name,target.name,entry.x,entry.z,target.x,target.z,search.distance[entry.id],best,List.copyOf(path),List.copyOf(stationIds));}
    private Search dijkstra(int start,Map<String,String>reports){double[] d=new double[stations.size()];Edge[]next=new Edge[stations.size()];Arrays.fill(d,Double.POSITIVE_INFINITY);d[start]=0;PriorityQueue<double[]>q=new PriorityQueue<>(Comparator.comparingDouble(a->a[1]));q.add(new double[]{start,0});while(!q.isEmpty()){double[] n=q.poll();int at=(int)n[0];if(n[1]!=d[at])continue;for(Edge e:graph.get(at)){if("OBSTRUCTED".equals(reports.get(reportKey(e.to))))continue;double nd=n[1]+e.distance;if(nd<d[e.to]){d[e.to]=nd;List<Point> reverse=new ArrayList<>(e.path);Collections.reverse(reverse);next[e.to]=new Edge(at,e.distance,List.copyOf(reverse),e.color,e.company,e.line);q.add(new double[]{e.to,nd});}}}return new Search(d,next);}
    private static final Map<TeleportRoute,Trip> ROUTE_TRIPS=Collections.synchronizedMap(new WeakHashMap<>());
    public static Trip tripFor(TeleportRoute route){return ROUTE_TRIPS.get(route);}
    public List<TeleportRoute> enrich(List<TeleportRoute> routes,double targetX,double targetZ,Map<String,String>reports){return enrich(routes,targetX,targetZ,reports,false);}
    public List<TeleportRoute> enrich(List<TeleportRoute> routes,double targetX,double targetZ,Map<String,String>reports,boolean accessibleOnly){Station target=nearest(targetX,targetZ,reports,accessibleOnly);if(target==null)return routes;Search search=dijkstra(target.id,reports);List<TeleportRoute> out=new ArrayList<>(routes.size());for(TeleportRoute r:routes){Trip trip=bestTrip(r.destination().x(),r.destination().z(),targetX,targetZ,target,search,reports,accessibleOnly);if(trip==null){out.add(r);continue;}List<TeleportRoute.Step>steps=new ArrayList<>(r.steps());steps.add(Math.max(0,steps.size()-1),new TeleportRoute.Step(TeleportRoute.StepType.ICE_ROAD,trip.entry+" → "+trip.exit,""));TeleportRoute enriched=new TeleportRoute(r.mode(),List.copyOf(steps),r.destination(),trip.effectiveDistance,r.membershipRisk(),r.quality(),r.joinHops(),trip.effectiveDistance,r.walkingDistance()-trip.effectiveDistance);ROUTE_TRIPS.put(enriched,trip);out.add(enriched);}return List.copyOf(out);}
}
