package net.earthmc.routefinder.gui;

import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.network.chat.Component;
import net.earthmc.routefinder.*;
import net.earthmc.routefinder.integration.XaeroWaypointBridge;
import net.earthmc.routefinder.teleport.*;
import java.util.*;

/** Compact, draggable Teleport Viewer drawn directly over Xaero's World Map. */
public final class TeleportViewerOverlay {
    private static final int W=360,HEADER=25,ROW=96,VISIBLE=4;
    private static boolean open,minimized,advanced,dragging,resultsCleared,advancedConfirmed;
    private static double targetX,targetZ,dragOffsetX,dragOffsetY;
    private static int selected,scroll;
    private static DestinationView destinationView=DestinationView.USABLE;
    private static ExitFilter exitFilter=ExitFilter.EVERYTHING;
    private static TeleportAccessService.Plan currentPlan;
    private static List<TeleportRoute> currentRoutes=List.of();
    private static java.util.concurrent.CompletableFuture<RouteResult> pendingRoutes;
    private static long routeGeneration,nextRoutePollAt;
    private static boolean cachedAdvanced,cachedTownSpawns,cachedNationSpawns,cachedIceRoads;
    private static DestinationView cachedDestinationView;
    private static String feedback="";private static long feedbackUntil;

    private TeleportViewerOverlay(){}

    public static void open(double x,double z){targetX=x;targetZ=z;open=true;minimized=false;RouteFinderConfig cfg=RouteFinderMod.getConfig();advanced=cfg.teleportAdvancedEnabled&&cfg.teleportDefaultAdvanced;destinationView=DestinationView.USABLE;exitFilter=ExitFilter.EVERYTHING;selected=scroll=0;resultsCleared=false;advancedConfirmed=false;feedback="";currentPlan=null;currentRoutes=List.of();pendingRoutes=null;routeGeneration++;nextRoutePollAt=0;RouteFinderMod.refreshTeleportData(x,z);}
    public static void stationReportChanged(){currentPlan=null;routeGeneration++;}
    public static boolean open(){return open;}
    public record MinimapRoute(double spawnX,double spawnZ,double targetX,double targetZ,double walkingDistance,net.earthmc.routefinder.ice.IceRoadNetwork.Trip ice){}
    /** Immutable snapshot consumed by the HUD thread; absent when the viewer has no active result. */
    public static Optional<MinimapRoute> minimapRoute(){TeleportRoute route=selectedRoute();if(!open||resultsCleared||route==null)return Optional.empty();return Optional.of(new MinimapRoute(route.destination().x(),route.destination().z(),targetX,targetZ,route.walkingDistance(),net.earthmc.routefinder.ice.IceRoadNetwork.tripFor(route)));}
    public static int panelWidth(){return W;}
    public static void close(){open=false;minimized=false;dragging=false;currentRoutes=List.of();}

    public static void render(GuiGraphics g,double camX,double camZ,double mapScale,int sw,int sh,RouteFinderConfig cfg){
        if(!open)return;if(!cfg.teleportAdvancedEnabled)advanced=false;
        if(!minimized&&!resultsCleared)refreshRoutes(cfg);
        if(dragging){Minecraft mc=Minecraft.getInstance();double mx=mc.mouseHandler.getScaledXPos(mc.getWindow()),my=mc.mouseHandler.getScaledYPos(mc.getWindow());cfg.teleportWindowX=Math.clamp((int)Math.round(mx-dragOffsetX),4,Math.max(4,sw-W-4));cfg.teleportWindowY=Math.clamp((int)Math.round(my-dragOffsetY),4,Math.max(4,sh-HEADER-4));}
        TeleportRoute route=selectedRoute();if(route!=null)drawRoute(g,camX,camZ,mapScale,sw,sh,cfg,route);
        int x=Math.clamp(cfg.teleportWindowX,4,Math.max(4,sw-W-4)),y=Math.clamp(cfg.teleportWindowY,4,Math.max(4,sh-HEADER-4));
        int topOffset=advanced?154:136;int h=minimized?HEADER:Math.min(sh-y-6,topOffset+VISIBLE*ROW+53);
        g.fill(x,y,x+W,y+h,0xFA071014);g.fill(x,y,x+W,y+HEADER,0xFF0D1820);
        g.drawString(Minecraft.getInstance().font,Component.translatable("earthmcroutefinder.teleport.title"),x+10,y+8,0xFFFFFFFF,false);
        g.drawString(Minecraft.getInstance().font,minimized?"+":"–",x+W-36,y+8,0xFFDDE7ED,false);g.drawString(Minecraft.getInstance().font,"×",x+W-17,y+8,0xFFFF9A9A,false);if(minimized)return;
        TeleportAccessService.Plan plan=currentPlan;
        g.drawString(Minecraft.getInstance().font,Component.translatable("earthmcroutefinder.teleport.destination_coords",(int)Math.round(targetX),(int)Math.round(targetZ)),x+10,y+34,0xFFE1E8ED,false);
        boolean routeLoading=pendingRoutes!=null||plan!=null&&plan.loading();
        drawRefreshButton(g,x+W-78,y+29,68,19,routeLoading);
        String membership=plan==null||plan.player()==null?Component.translatable(routeLoading?"earthmcroutefinder.teleport.loading":"earthmcroutefinder.teleport.eligibility_reason.api_data_missing").getString():plan.player().town()+" / "+plan.player().nation();
        g.drawString(Minecraft.getInstance().font,membership,x+10,y+48,0xFFB5C0C8,false);
        g.fill(x+8,y+65,x+(cfg.teleportAdvancedEnabled?W/2-2:W-8),y+85,0xFF245F50);g.drawCenteredString(Minecraft.getInstance().font,Component.translatable("earthmcroutefinder.teleport.mode.standard"),x+(cfg.teleportAdvancedEnabled?W/4:W/2),y+71,0xFFFFFFFF);
        if(cfg.teleportAdvancedEnabled){g.fill(x+W/2+2,y+65,x+W-8,y+85,advanced?0xFF6B4A24:0xFF26333A);g.drawCenteredString(Minecraft.getInstance().font,Component.translatable("earthmcroutefinder.teleport.mode.advanced"),x+3*W/4,y+71,0xFFFFFFFF);}
        boolean locked=advancedLocked();
        if(advanced)g.drawString(Minecraft.getInstance().font,Component.translatable(locked?"earthmcroutefinder.teleport.advanced.locked":"earthmcroutefinder.teleport.advanced.clipboard_only"),x+10,y+92,locked?0xFFFF9A9A:0xFFFFC06A,false);
        int destinationViewY=y+(advanced?108:90);
        drawDestinationViewButtons(g,x+8,destinationViewY,cfg);
        drawExitFilterButtons(g,x+8,destinationViewY+22);
        int top=y+topOffset;
        for(int i=scroll;i<Math.min(currentRoutes.size(),scroll+VISIBLE);i++)drawRouteRow(g,currentRoutes.get(i),i,x,top+(i-scroll)*ROW,locked);
        if(System.currentTimeMillis()<feedbackUntil&&!feedback.isBlank())g.drawString(Minecraft.getInstance().font,feedback,x+10,y+h-31,0xFFFFCC66,false);
        if(routeLoading&&!resultsCleared)g.drawString(Minecraft.getInstance().font,Component.translatable("earthmcroutefinder.teleport.loading"),x+10,y+h-18,0xFFFFFF77,false);
        else if(currentRoutes.isEmpty()&&!resultsCleared)g.drawString(Minecraft.getInstance().font,Component.translatable(advanced&&cfg.teleportPrimaryHomeTown.isBlank()?"earthmcroutefinder.teleport.primary_required":"earthmcroutefinder.teleport.none"),x+10,y+h-18,0xFFFFAA66,false);
        else if(!currentRoutes.isEmpty())drawFooter(g,x,y+h,locked);
        else g.drawString(Minecraft.getInstance().font,Component.translatable("earthmcroutefinder.teleport.results_cleared"),x+10,y+h-18,0xFFAFBAC2,false);
    }

    private static void drawRouteRow(GuiGraphics g,TeleportRoute route,int index,int x,int y,boolean locked){
        int bg=locked?0xEE24282B:index==selected?0xFF244F42:0xF0132420,text=locked?0xFF858B93:0xFFFFFFFF;
        g.fill(x+8,y,x+W-8,y+ROW-3,bg);
        g.drawString(Minecraft.getInstance().font,(route.destination().type()==TeleportDestination.Type.TOWN_SPAWN?"T · ":"N · ")+route.destination().name(),x+14,y+4,text,false);
        g.drawString(Minecraft.getInstance().font,Component.translatable("earthmcroutefinder.teleport.blocks",(int)Math.round(route.walkingDistance())),x+W-100,y+4,text,false);
        int commandColor=locked?0xFF70777C:0xFF8BE5BB;
        if(advanced){String join=stepCommand(route,TeleportRoute.StepType.JOIN_TOWN);if(!join.isBlank())drawCommandButton(g,x+14,y+17,W-28,14,join,commandColor,!locked);drawCommandButton(g,x+14,y+34,W-28,14,route.destination().command(),commandColor,!locked);g.drawString(Minecraft.getInstance().font,quality(route),x+14,y+51,locked?0xFF777D82:qualityColor(route),false);g.drawString(Minecraft.getInstance().font,reason(route),x+14,y+63,locked?0xFF777D82:0xFFADB9C1,false);}
        else{drawCommandButton(g,x+14,y+20,W-28,17,route.destination().command(),commandColor,true);g.drawString(Minecraft.getInstance().font,reason(route),x+14,y+44,route.destination().eligibility()==TeleportDestination.Eligibility.UNCERTAIN?0xFFFFC85C:0xFFADB9C1,false);String ice=stepLabel(route,TeleportRoute.StepType.ICE_ROAD);if(!ice.isBlank())g.drawString(Minecraft.getInstance().font,Component.translatable("earthmcroutefinder.teleport.ice_roads",ice),x+14,y+57,0xFF8FD9FF,false);}
        drawTraversalButtons(g,x+14,y+73,route.destination().physicalAccess(),locked);
    }
    private static void drawTraversalButtons(GuiGraphics g,int x,int y,TeleportDestination.PhysicalAccess selected,boolean locked){TeleportDestination.PhysicalAccess[] values=TeleportDestination.PhysicalAccess.values();for(int i=0;i<values.length;i++){TeleportDestination.PhysicalAccess value=values[i];int bx=x+i*112,bg=locked?0xFF20272B:value==selected?statusColor(value):0xFF27373D,color=locked?0xFF747C80:value==selected?0xFFFFFFFF:0xFFB9C5CB;g.fill(bx,y,bx+108,y+17,bg);g.drawCenteredString(Minecraft.getInstance().font,Component.translatable("earthmcroutefinder.teleport.traversal.button."+value.name().toLowerCase(Locale.ROOT)),bx+54,y+4,color);}}
    private static int statusColor(TeleportDestination.PhysicalAccess access){return switch(access){case UNKNOWN->0xFF45545B;case ACCESSIBLE->0xFF245F50;case OBSTRUCTED->0xFF692E2E;};}
    private static void drawDestinationViewButtons(GuiGraphics g,int x,int y,RouteFinderConfig cfg){DestinationView[] values=DestinationView.values();for(int i=0;i<values.length;i++){DestinationView value=values[i];int bx=x+i*116;boolean active=value==destinationView;g.fill(bx,y,bx+112,y+18,active?0xFF245F50:0xFF1B2931);g.fill(bx,y+16,bx+112,y+18,active?0xFF65DDB4:0xFF41515B);g.drawCenteredString(Minecraft.getInstance().font,Component.translatable("earthmcroutefinder.teleport.view."+value.name().toLowerCase(Locale.ROOT)),bx+56,y+5,active?0xFFFFFFFF:0xFFB9C5CB);}int bx=x+232;g.fill(bx,y,bx+112,y+18,cfg.teleportIncludeIceRoads?0xFF245F50:0xFF1B2931);g.fill(bx,y+16,bx+112,y+18,cfg.teleportIncludeIceRoads?0xFF65DDB4:0xFF41515B);g.drawCenteredString(Minecraft.getInstance().font,Component.translatable("earthmcroutefinder.teleport.ice_roads",Component.translatable(cfg.teleportIncludeIceRoads?"options.on":"options.off")),bx+56,y+5,cfg.teleportIncludeIceRoads?0xFFFFFFFF:0xFFB9C5CB);}
    private static void drawExitFilterButtons(GuiGraphics g,int x,int y){ExitFilter[] values=ExitFilter.values();for(int i=0;i<values.length;i++){ExitFilter value=values[i];int bx=x+i*116;boolean active=value==exitFilter;g.fill(bx,y,bx+112,y+18,active?0xFF315E70:0xFF1B2931);g.fill(bx,y+16,bx+112,y+18,active?0xFF7EDCF2:0xFF41515B);g.drawCenteredString(Minecraft.getInstance().font,Component.translatable("earthmcroutefinder.teleport.filter."+value.name().toLowerCase(Locale.ROOT)),bx+56,y+5,active?0xFFFFFFFF:0xFFB9C5CB);}}
    private static void drawCommandButton(GuiGraphics g,int x,int y,int w,int h,String command,int color,boolean enabled){Minecraft mc=Minecraft.getInstance();double mx=mc.mouseHandler.getScaledXPos(mc.getWindow()),my=mc.mouseHandler.getScaledYPos(mc.getWindow());boolean hovered=enabled&&mx>=x&&mx<x+w&&my>=y&&my<y+h;int bg=!enabled?0xFF182126:hovered?0xFF294651:0xFF1A2A31,border=hovered?0xFF65DDB4:0xFF3C555F;g.fill(x,y,x+w,y+h,bg);g.fill(x,y,x+w,y+1,border);g.fill(x,y+h-2,x+w,y+h,border);g.fill(x,y,x+1,y+h,border);g.fill(x+w-1,y,x+w,y+h,border);g.drawCenteredString(mc.font,command,x+w/2,y+3,color);}
    private static Component reason(TeleportRoute route){return Component.translatable("earthmcroutefinder.teleport.eligibility_reason."+route.destination().reason().name().toLowerCase(Locale.ROOT));}
    private static Component quality(TeleportRoute route){TeleportRouteQuality.Rating rating=TeleportRouteQuality.rate(route.saving());long blocks=TeleportRouteQuality.blockDifference(route.saving());String key=rating==TeleportRouteQuality.Rating.LONGER?"earthmcroutefinder.teleport.quality.longer":"earthmcroutefinder.teleport.quality."+rating.name().toLowerCase(Locale.ROOT);return Component.translatable(key,blocks);}
    private static int qualityColor(TeleportRoute route){return switch(TeleportRouteQuality.rate(route.saving())){case EXCELLENT->0xFF66E6A4;case GOOD->0xFF8BE5BB;case SLIGHT_IMPROVEMENT->0xFFB7DFAE;case SAME_DISTANCE->0xFFC0C7CC;case LONGER->0xFFFFA66B;case NOT_COMPARABLE->0xFFFFC85C;};}
    private static void drawFooter(GuiGraphics g,int x,int bottom,boolean locked){int y=bottom-44;drawFooterButton(g,x+8,y,166,18,"earthmcroutefinder.teleport.clear_results",0xFFFF9A9A);drawFooterButton(g,x+178,y,174,18,"earthmcroutefinder.teleport.remove_waypoints",0xFFFFC06A);y+=20;if(locked)drawFooterButton(g,x+8,y,W-16,18,"earthmcroutefinder.teleport.advanced.confirm",0xFFFFC06A);else drawFooterButton(g,x+8,y,W-16,18,"earthmcroutefinder.teleport.target_waypoint",0xFF7EDCF2);}
    private static void drawFooterButton(GuiGraphics g,int x,int y,int w,int h,String key,int color){g.fill(x,y,x+w,y+h,0xFF1B2931);g.fill(x,y+h-2,x+w,y+h,0xFF41515B);g.drawCenteredString(Minecraft.getInstance().font,Component.translatable(key),x+w/2,y+5,color);}
    private static void drawRefreshButton(GuiGraphics g,int x,int y,int w,int h,boolean loading){Minecraft mc=Minecraft.getInstance();double mx=mc.mouseHandler.getScaledXPos(mc.getWindow()),my=mc.mouseHandler.getScaledYPos(mc.getWindow());boolean hovered=!loading&&mx>=x&&mx<x+w&&my>=y&&my<y+h;g.fill(x,y,x+w,y+h,loading?0xFF182126:hovered?0xFF294651:0xFF1B2931);g.fill(x,y+h-2,x+w,y+h,hovered?0xFF65DDB4:0xFF41515B);g.drawCenteredString(mc.font,Component.translatable(loading?"earthmcroutefinder.common.refreshing":"earthmcroutefinder.common.refresh"),x+w/2,y+5,loading?0xFF7F898F:0xFF8BE5BB);}
    private static void drawRoute(GuiGraphics g,double camX,double camZ,double scale,int sw,int sh,RouteFinderConfig cfg,TeleportRoute route){double ax=sw/2.0+(route.destination().x()-camX)*scale,ay=sh/2.0+(route.destination().z()-camZ)*scale,tx=sw/2.0+(targetX-camX)*scale,ty=sh/2.0+(targetZ-camZ)*scale;var ice=net.earthmc.routefinder.ice.IceRoadNetwork.tripFor(route);boolean drewIce=cfg.teleportRouteLineVisible&&IceRoadOverlay.renderSelectedRoute(g,camX,camZ,scale,sw,sh,route.destination().x(),route.destination().z(),targetX,targetZ,ice,cfg);if(cfg.teleportRouteLineVisible&&!drewIce){int steps=TeleportRenderBudget.lineSteps(Math.hypot(tx-ax,ty-ay));for(int i=0;i<=steps;i+=2){double t=i/(double)steps;int px=(int)Math.round(ax+(tx-ax)*t),py=(int)Math.round(ay+(ty-ay)*t);if(px>=-2&&px<=sw+2&&py>=-2&&py<=sh+2)g.fill(px-1,py-1,px+2,py+2,0xFFFF58D0);}int lx=(int)((ax+tx)/2),ly=(int)((ay+ty)/2);if(lx>=-30&&lx<=sw+30&&ly>=-10&&ly<=sh+10){g.fill(lx-27,ly-8,lx+28,ly+7,0xCC171019);g.drawCenteredString(Minecraft.getInstance().font,(int)Math.round(route.walkingDistance())+" blocks",lx,ly-4,0xFFFFFFFF);}}if(cfg.teleportArrivalMarkerVisible&&ax>=-8&&ax<=sw+8&&ay>=-8&&ay<=sh+8){g.fill((int)ax-5,(int)ay-5,(int)ax+6,(int)ay+6,0xFFFFB13B);g.fill((int)ax-2,(int)ay-2,(int)ax+3,(int)ay+3,0xFFFFFFFF);}if(cfg.teleportDestinationMarkerVisible&&tx>=-8&&tx<=sw+8&&ty>=-8&&ty<=sh+8){g.fill((int)tx-5,(int)ty-5,(int)tx+6,(int)ty+6,0xFF23C7E8);g.fill((int)tx-2,(int)ty-2,(int)tx+3,(int)ty+3,0xFFFFFFFF);}}

    public static boolean click(double mx,double my,int sw,int sh,RouteFinderConfig cfg){
        if(!open)return false;if(IceRoadOverlay.clickSelectedRoute(mx,my,sw,sh,cfg)){currentPlan=null;routeGeneration++;return true;}int x=Math.clamp(cfg.teleportWindowX,4,Math.max(4,sw-W-4)),y=Math.clamp(cfg.teleportWindowY,4,Math.max(4,sh-HEADER-4));int topOffset=advanced?154:136;int h=Math.min(sh-y-6,topOffset+VISIBLE*ROW+53);
        if(mx<x||mx>x+W||my<y||my>y+(minimized?HEADER:h))return false;
        if(my<y+HEADER){if(mx>x+W-25)close();else if(mx>x+W-50)minimized=!minimized;else{dragging=true;dragOffsetX=mx-x;dragOffsetY=my-y;}return true;}
        if(minimized)return true;
        if(mx>=x+W-78&&mx<x+W-10&&my>=y+29&&my<y+48){if(currentPlan==null||!currentPlan.loading()){resultsCleared=false;currentPlan=null;currentRoutes=List.of();selected=scroll=0;routeGeneration++;RouteFinderMod.forceRefreshTeleportData(targetX,targetZ);}return true;}
        if(my>=y+65&&my<=y+87&&cfg.teleportAdvancedEnabled){boolean nextAdvanced=mx>=x+W/2;if(advanced!=nextAdvanced){advanced=nextAdvanced;routeGeneration++;}advancedConfirmed=false;selected=scroll=0;return true;}
        int destinationViewY=y+(advanced?108:90);if(my>=destinationViewY&&my<destinationViewY+18){if(mx>=x+240&&mx<x+352){cfg.teleportIncludeIceRoads=!cfg.teleportIncludeIceRoads;cfg.save();currentPlan=null;routeGeneration++;selected=scroll=0;return true;}DestinationView view=destinationViewAt(mx,x+8);if(view!=null&&view!=destinationView){destinationView=view;selected=scroll=0;currentPlan=null;routeGeneration++;}return true;}
        int filterY=destinationViewY+22;if(my>=filterY&&my<filterY+18){ExitFilter filter=exitFilterAt(mx,x+8);if(filter!=null&&filter!=exitFilter){exitFilter=filter;selected=scroll=0;currentPlan=null;routeGeneration++;}return true;}
        int footer=y+h-48;if(my>=footer&&!currentRoutes.isEmpty()){if(my<footer+20){if(mx<x+176)clearResults();else{boolean removed=XaeroWaypointBridge.removeTeleportWaypoints();feedback=Component.translatable(removed?"earthmcroutefinder.teleport.waypoints_removed":"earthmcroutefinder.teleport.no_waypoints").getString();feedbackUntil=System.currentTimeMillis()+1_600;}}else if(advancedLocked())advancedConfirmed=true;else setRouteWaypoints();return true;}
        int top=y+topOffset,index=scroll+(int)((my-top)/ROW);if(index>=scroll&&index<currentRoutes.size()&&index<scroll+VISIBLE){TeleportRoute route=currentRoutes.get(index);int rowY=top+(index-scroll)*ROW;if(!advancedLocked()&&my>=rowY+73&&my<rowY+90){TeleportDestination.PhysicalAccess access=accessButtonAt(mx,x+14);if(access!=null){RouteFinderMod.setTeleportSpawnReport(route.destination(),access);currentPlan=null;routeGeneration++;}return true;}boolean insideCommandX=mx>=x+14&&mx<x+W-14;if(!advancedLocked()&&insideCommandX){if(advanced&&my>=rowY+17&&my<rowY+31){String join=stepCommand(route,TeleportRoute.StepType.JOIN_TOWN);if(!join.isBlank()){selected=index;perform(join,route);}return true;}if(advanced&&my>=rowY+34&&my<rowY+48){selected=index;perform(route.destination().command(),route);return true;}if(!advanced&&my>=rowY+20&&my<rowY+37){selected=index;perform(route.destination().command(),route);return true;}}selected=index;return true;}return true;
    }
    private static void perform(String command,TeleportRoute route){TeleportCommandAction.Result result=TeleportCommandAction.perform(command,RouteFinderMod.getConfig().teleportCommandAction,advanced,route.destination().eligibility()==TeleportDestination.Eligibility.ACCESSIBLE);feedback=Component.translatable("earthmcroutefinder.teleport.command_result."+result.name().toLowerCase(Locale.ROOT)).getString();feedbackUntil=System.currentTimeMillis()+1_600;if(result==TeleportCommandAction.Result.EXECUTED){Minecraft mc=Minecraft.getInstance();if(mc!=null)mc.setScreen(null);}}
    private static String stepCommand(TeleportRoute route,TeleportRoute.StepType type){return route.steps().stream().filter(s->s.type()==type).map(TeleportRoute.Step::command).filter(s->s!=null&&!s.isBlank()).findFirst().orElse("");}
    private static String stepLabel(TeleportRoute route,TeleportRoute.StepType type){return route.steps().stream().filter(s->s.type()==type).map(TeleportRoute.Step::label).filter(s->s!=null&&!s.isBlank()).findFirst().orElse("");}
    private static boolean advancedLocked(){return advanced&&!advancedConfirmed&&currentPlan!=null&&AdvancedCommandGuard.requiresConfirmation(currentPlan.player());}
    public static boolean release(RouteFinderConfig cfg){if(!dragging)return false;dragging=false;cfg.save();return true;}
    public static boolean scroll(double mx,double my,double amount,int sw,int sh,RouteFinderConfig cfg){if(!open)return false;int x=cfg.teleportWindowX,y=cfg.teleportWindowY;if(mx<x||mx>x+W||my<y||my>y+434)return false;int max=Math.max(0,currentRoutes.size()-VISIBLE);scroll=Math.clamp(scroll-(int)Math.signum(amount),0,max);selected=Math.clamp(selected,0,Math.max(0,currentRoutes.size()-1));return true;}
    private static List<TeleportRoute> routes(){return currentRoutes;}
    private static void refreshRoutes(RouteFinderConfig cfg){
        if(pendingRoutes!=null&&pendingRoutes.isDone()){RouteResult result=null;try{result=pendingRoutes.join();}catch(java.util.concurrent.CompletionException e){RouteFinderMod.LOGGER.warn("[TownyMap] Teleport route calculation failed",e.getCause());}pendingRoutes=null;if(result!=null&&result.generation==routeGeneration){boolean planChanged=result.plan!=currentPlan;if(planChanged&&AdvancedCommandGuard.requiresConfirmation(result.plan.player()))advancedConfirmed=false;currentPlan=result.plan;currentRoutes=result.routes;cachedAdvanced=result.advanced;cachedTownSpawns=result.showTowns;cachedNationSpawns=result.showNations;cachedDestinationView=result.view;cachedIceRoads=result.iceRoads;selected=Math.clamp(selected,0,Math.max(0,currentRoutes.size()-1));scroll=Math.clamp(scroll,0,Math.max(0,currentRoutes.size()-VISIBLE));nextRoutePollAt=System.currentTimeMillis()+100;}}
        boolean settingsCurrent=currentPlan!=null&&cachedAdvanced==advanced&&cachedTownSpawns==cfg.teleportShowTownSpawns&&cachedNationSpawns==cfg.teleportShowNationSpawns&&cachedDestinationView==destinationView&&cachedIceRoads==cfg.teleportIncludeIceRoads;
        if(pendingRoutes!=null||settingsCurrent&&!currentPlan.loading()||settingsCurrent&&System.currentTimeMillis()<nextRoutePollAt)return;
        long generation=routeGeneration;boolean useAdvanced=advanced,showTowns=cfg.teleportShowTownSpawns,showNations=cfg.teleportShowNationSpawns,iceRoads=cfg.teleportIncludeIceRoads;DestinationView view=destinationView;ExitFilter filter=exitFilter;double x=targetX,z=targetZ;Map<String,String> reports=Map.copyOf(cfg.iceRoadStationReports);
        pendingRoutes=RouteFinderMod.teleportPlanAsync(x,z).thenApplyAsync(plan->{List<TeleportRoute> base=useAdvanced?plan.advanced():plan.standard();List<TeleportRoute> routes=filterRoutes(base,showTowns,showNations,view,filter);if(iceRoads)routes=net.earthmc.routefinder.ice.IceRoadNetwork.get().enrich(routes,x,z,reports,filter==ExitFilter.ACCESSIBLE);routes=routes.stream().sorted(java.util.Comparator.comparingDouble(TeleportRoute::walkingDistance)).toList();return new RouteResult(generation,plan,routes,useAdvanced,showTowns,showNations,view,iceRoads);});
    }
    private record RouteResult(long generation,TeleportAccessService.Plan plan,List<TeleportRoute> routes,boolean advanced,boolean showTowns,boolean showNations,DestinationView view,boolean iceRoads){}
    static List<TeleportRoute> filterRoutes(List<TeleportRoute> routes,boolean showTowns,boolean showNations,boolean ignoredShowUncertain,boolean ignoredShowObstructed){return filterRoutes(routes,showTowns,showNations,ExitFilter.EVERYTHING);}
    static List<TeleportRoute> filterRoutes(List<TeleportRoute> routes,boolean showTowns,boolean showNations,ExitFilter filter){return filterRoutes(routes,showTowns,showNations,DestinationView.ALL_SPAWNS,filter);}
    static List<TeleportRoute> filterRoutes(List<TeleportRoute> routes,boolean showTowns,boolean showNations,DestinationView view,ExitFilter filter){return routes.stream().filter(r->showTowns||r.destination().type()!=TeleportDestination.Type.TOWN_SPAWN).filter(r->showNations||r.destination().type()!=TeleportDestination.Type.NATION_SPAWN).filter(r->view==DestinationView.ALL_SPAWNS||r.destination().eligibility()==TeleportDestination.Eligibility.ACCESSIBLE).filter(r->filter==ExitFilter.EVERYTHING||filter==ExitFilter.ACCESSIBLE&&r.destination().physicalAccess()==TeleportDestination.PhysicalAccess.ACCESSIBLE||filter==ExitFilter.BLOCKED&&r.destination().physicalAccess()==TeleportDestination.PhysicalAccess.OBSTRUCTED).toList();}
    static TeleportDestination.PhysicalAccess accessButtonAt(double mouseX,int left){for(int i=0;i<3;i++){int x=left+i*112;if(mouseX>=x&&mouseX<x+108)return TeleportDestination.PhysicalAccess.values()[i];}return null;}
    static ExitFilter exitFilterAt(double mouseX,int left){for(int i=0;i<3;i++){int x=left+i*116;if(mouseX>=x&&mouseX<x+112)return ExitFilter.values()[i];}return null;}
    static DestinationView destinationViewAt(double mouseX,int left){for(int i=0;i<2;i++){int x=left+i*116;if(mouseX>=x&&mouseX<x+112)return DestinationView.values()[i];}return null;}
    enum DestinationView{USABLE,ALL_SPAWNS}
    enum ExitFilter{EVERYTHING,ACCESSIBLE,BLOCKED}
    private static TeleportRoute selectedRoute(){if(currentRoutes.isEmpty())return null;selected=Math.clamp(selected,0,currentRoutes.size()-1);return currentRoutes.get(selected);}
    public static void setArrivalWaypoint(){setRouteWaypoints();}
    private static void setRouteWaypoints(){TeleportRoute route=selectedRoute();if(route==null)return;List<XaeroWaypointBridge.RouteWaypoint> points=new ArrayList<>();points.add(new XaeroWaypointBridge.RouteWaypoint(Component.translatable("earthmcroutefinder.teleport.waypoint.teleport",route.destination().name()).getString(),route.destination().x(),route.destination().y(),route.destination().z()));var ice=net.earthmc.routefinder.ice.IceRoadNetwork.tripFor(route);if(ice!=null){points.add(new XaeroWaypointBridge.RouteWaypoint(Component.translatable("earthmcroutefinder.teleport.waypoint.ice_entry",ice.entry()).getString(),(int)Math.round(ice.entryX()),0,(int)Math.round(ice.entryZ())));if(ice.exitId()!=ice.entryId())points.add(new XaeroWaypointBridge.RouteWaypoint(Component.translatable("earthmcroutefinder.teleport.waypoint.ice_exit",ice.exit()).getString(),(int)Math.round(ice.exitX()),0,(int)Math.round(ice.exitZ())));}String destination=RouteFinderMod.teleportTownName(targetX,targetZ);if(destination==null||destination.isBlank())destination=Component.translatable("earthmcroutefinder.teleport.target").getString();points.add(new XaeroWaypointBridge.RouteWaypoint(Component.translatable("earthmcroutefinder.teleport.waypoint.destination",destination).getString(),(int)Math.round(targetX),0,(int)Math.round(targetZ)));boolean created=XaeroWaypointBridge.replaceTeleportRouteWaypoints(points);feedback=Component.translatable(created?"earthmcroutefinder.teleport.route_waypoints_set":"earthmcroutefinder.teleport.route_waypoints_failed",points.size()).getString();feedbackUntil=System.currentTimeMillis()+1_600;}
    private static void clearResults(){resultsCleared=true;selected=scroll=0;currentPlan=null;currentRoutes=List.of();routeGeneration++;}
}
